name: build
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::10"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{needs.job1.outputs.matrix}}
    steps:
      - run: echo ${{needs.job1.outputs.matrix}}