name: TESTE
on: [push]
                       
env: # Definir nossas env
  token: 123456789 # Como por exemplo

jobs: # Serviço que será feito
  deploy: # Nome do serviço
    runs-on: ubuntu-latest # Qual VM iremos executar
    outputs:
      matrix: ${{ steps.test-percentage.outputs }}

    steps: # Etapas
      - name: Checkout repository
        uses: actions/checkout@v2 # Quando utilizamos uma lib devemos colocar o uses

      - name: Install Dependencies
        run: yarn  

      - name: Test repository
        run: yarn test:coverage

      - name: teste if
        id: test-percentage
        run: |
          json=`cat ./coverage/coverage-summary.json`
          echo `echo $(jq -r '.total.lines.pct' <<< "$json")`
      
      - name: lala
        if: ( ${{steps.test-percentage.outputs}} == 'a' )
        run: echo 'chegou'

        