name: GitHub Pages

on:
  pull_request:
    branches: 
      - main

env:
  token: 123456789

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Realizar um checkout no repositorio
      - uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Install dependecies
        run: yarn install

      - name: Check eslint
        run: yarn lint

      - name: Check for listing errors
        run: yarn test