name: GitHub Pages

on:
  push:
    branches:
      - dev
  pull_request:
    branches: 
      - main
      - dev
			
env:
	token: 123456789

jobs:
	deploy:
		runs-on: ubuntu-latest

		steps:
			- name: Realizar um checkout no repositorio
			- uses: actions/checkout@v2
				with:
					node-version: '16'

			- uses: Install dependecies
				run: yarn install

			-uses: Check eslint
				run: yarn lint
			
			

			- uses: Check for listing errors
				run: yarn test