name: GitHub Pages 1

on:
  pull_request:
    branches: 
      - main

env:
  token: 123456789

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependeciesa
        run: yarn install