# name: Check code for PullRequest# Definimos o nome da ação
# on: # Quando a ação será executada                     
#   pull_request:                      
#     branches:                        
#       - main
                       
# jobs: # Serviço que será feito
#   deploy: # Nome do serviço
#     runs-on: ubuntu-latest # Qual VM iremos executar

#     steps: # Etapas
#       - name: Checkout repository
#         uses: actions/checkout@v2 # Quando utilizamos uma lib devemos colocar o uses

#       - name: Install Node
#         uses: actions/setup-node@v2
#         with:
#             node-version: '16' # Qual versão do node utilizaremos

#       - name: Install dependecies
#         run: yarn install # Instalar as dependecias
