name: GitHub Pages # Definimos o nome da ação
on: # Quando a ação será executada  
  push:
    branches:
      - main

jobs: # Serviços que será feito
  deploy: # Nome do serviço
    runs-on: ubuntu-latest # Qual VM iremos executar
    steps: # Etapas
       - name: Checkout repository # Nome que será exibido na action
         uses: actions/checkout@v2 # Quando utilizamos uma lib devemos colocar o uses

      - name: Setup Node
        uses: actions/setup-node@v2 # Lib para instalar o node em nossa VM
          with:
            node-version: '16' # Qual versão do node utilizaremos

      - name: Install dependecies
        run: yarn install # Instalar as dependecias

      - name: Build
        run: yarn  build # Construir nossa aplicação

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Esta secret o github pega automaticamente, não precisamos defini-la
          publish_dir: ./build # Pasta o qual contem o projeto contruído